(uiop:define-package #:40ants-doc/commondoc/page
  (:use #:cl)
  (:import-from #:common-doc)
  (:import-from #:common-html.emitter)
  (:import-from #:40ants-doc/commondoc/html
                #:with-html)
  (:import-from #:common-html.emitter
                #:define-emitter)
  (:import-from #:40ants-doc/commondoc/toc)
  (:export
   #:ensure-page
   #:make-page
   #:page))
(in-package 40ants-doc/commondoc/page)


(defclass page (common-doc:content-node)
  ((html-filename :type pathname
                  :reader html-filename
                  :initarg :html-filename)))


(defun make-page (sections html-filename)
  (make-instance 'page
                 :children (uiop:ensure-list sections)
                 :html-filename html-filename))


(defun ensure-page (obj)
  (check-type obj common-doc:document-node)
  (typecase obj
    (page obj)
    (t (make-page obj))))


(define-emitter (obj page)
  "Emit an piece of documentation."
  (let ((toc (40ants-doc/commondoc/toc:make-toc obj)))
    (with-html
      (:html
       (:head
        (:meta :name "viewport"
               :content "width=device-width, initial-scale=1")
        (:title "Example page")
        (:link :rel "stylesheet"
               :type "text/css"
               :href "theme.css"))
       (:body
        (:div :id "content-container"
              (:div :id "toc"
                    (:div :id "page-toc"
                          (common-html.emitter::emit toc))
                    (:div :id "toc-footer"
                          (:a :href "https://40ants.com/doc"
                              "[generated by 40ANTS-DOC]")))
              (:div :id "content"
                    (mapc #'common-html.emitter::emit
                          (common-doc::children obj)))))))))
