name: 'Run Tests'

on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    # Rerun tests at 10 AM every Monday
    # to check if they still work with latest dependencies.
    - cron:  '0 10 * * 1'

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show env
        run: 'env | sort -u'
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Check CL Version
        run: |
          ros install 40ants/cl-info
          cl-info
      - name: Install Qlot
        run: |
          ros install qlot
      - name: Install Dependencies
        run: |
          echo dist ultralisp http://dist.ultralisp.org/
          qlot install
      - name: Run tests
        run: |
          qlot exec ros run \
             --eval '(if (asdf:test-system :mgl-pax)
                        (uiop:quit 0)
                        (uiop:quit 1))'
