name: 'Run Tests'

on:
  # This will run tests on pushes
  # to master branch or on pull merges:
  push:
    branches:
      - 'main'
      - 'master'
  # This will run tests for every pull request:
  pull_request:
  # Rerun tests at 10 AM every Monday
  # to check if they still work with latest dependencies.
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
        os:
          - ubuntu-latest
          - macos-latest
        quicklisp-dist:
          - quicklisp
          - ultralisp
          
    runs-on: ${{ matrix.os }}
    
    env:
      LISP: ${{ matrix.lisp }}
      OS: ${{ matrix.os }}
      QUICKLISP_DIST: ${{ matrix.quicklisp-dist }}

    steps:
      - uses: actions/checkout@v1
      - name: Show env
        run: |
          env | sort -u
      - name: Install Roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Upgrade ASDF to the latest version
        run: |
          ros install asdf
      - name: Install Qlot
        run: |
          ros install qlot
      - name: Install Dependencies
        run: |
          rm -fr qlfile
          touch qlfile
          
          if [[ "${QUICKLISP_DIST}" == 'ultralisp' ]]; then
              echo dist ultralisp http://dist.ultralisp.org/ >> qlfile
          fi

          qlot install
          echo .qlot/bin >> $GITHUB_PATH
      - name: Check CL Version
        run: |
          qlot exec ros install 40ants/cl-info
          qlot exec cl-info
      - name: Run tests
        run: |
          qlot exec ros run \
             --eval '(if (asdf:test-system :mgl-pax)
                        (uiop:quit 0)
                        (uiop:quit 1))'
